name: build

on: [push, pull_request, release]

jobs:
    test:
      runs-on: ubuntu-latest
      steps:

      - uses: actions/checkout@master

      - name: Checkout qwc-docker
        uses: actions/checkout@master
        with:
          repository: qwc-services/qwc-docker
          path: qwc-docker

      - name: Start demo database
        run: |
          cd qwc-docker
          sed -i 's|jasper-reporting-service:8080|localhost:8002|' demo-config/default/documentConfig.json
          sed -i 's|\"document_templates\": \[\]|\"document_templates\": \[\"demo\"\]|g' demo-config/default/permissions.json
          docker-compose -f docker-compose-example.yml up -d jasper-reporting-service

      - name: Setting up python 3.6
        uses: actions/setup-python@v2
        with:
            python-version: '3.6'

      - name: Run unittests
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          CONFIG_PATH=$PWD/qwc-docker/demo-config/ python test.py

    build:
      needs: test
      runs-on: ubuntu-latest
      if: github.event_name == 'release' && github.event.action == 'created'
      steps:

      - uses: actions/checkout@master
      - name: Get version tag
        id: get_tag
        run: |
          if [ ${{ startsWith(github.ref, 'refs/tags/') }} = true ]; then
            echo ::set-output name=tag::latest,${GITHUB_REF:10}
          else
            echo ::set-output name=tag::latest
          fi

      - name: Build and publish docker image
        uses: elgohr/Publish-Docker-Github-Action@2.12
        with:
          name: sourcepole/${{ github.event.repository.name }}
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          tags: "${{ steps.get_tag.outputs.tag }}"
